---
title: "ESM 201 Assignment 1"
author: "Brad Anderson"
date: "February 9, 2018"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}

library(tidyverse)
library(stargazer)
library(car)
library(knitr)

```

```{r data, include=FALSE}

countries <- read_csv("~/github/eco1/data/countries.csv")

countries$population <- countries$population/1000

```

```{r create two dataframes, include=FALSE}

ugandadf <- countries %>% 
  filter( country == "Uganda")


```

```{r uganda growth rate}

plot(ugandadf$year, ugandadf$population, xlab="year", ylab="world population")

```

```{r Nt-1, include=FALSE}

ugandadf$yearminus1<-(ugandadf$year-1) # add a column for the previous year 

# Create N_(t-1) column 
ugandadf$popminus1<-ugandadf$population[match(ugandadf$yearminus1, ugandadf$year)]

```

```{r dn/ndt}

ugandadf$dNNdt<-log(ugandadf$population/ugandadf$popminus1)*1/(ugandadf$year-ugandadf$yearminus1)

#Plot results
plot(ugandadf$population, ugandadf$dNNdt, xlab="Nt", ylab="dN/Ndt")  # N OR N-1 HERE?

plot(ugandadf$year, ugandadf$dNNdt, xlab="year", ylab="dN/Ndt")
```

```{r uganda models}

ugandalm_1<-lm(dNNdt~population, data=ugandadf[ugandadf$year<=1980,])
ugandalm_2<-lm(dNNdt~population, data=ugandadf[ugandadf$year>1980,])
ugandalm_3<-lm(dNNdt~population, data=ugandadf)

par(mfrow=c(2,2))
plot(ugandalm_1) 

par(mfrow=c(2,2)) #Set parameters for plotting a 2x2 window
plot(ugandalm_2) # need to run this line at the same time as the one above to get 4-panel plot

summary(ugandalm_2
        )

```
y=5.43e-05x + 3.14e-02

Four assumptions of multiple regression:
• Linearity
• Independence
• Homoscedasticity (residuals variance)
• Normality


Diagnostic plots seem OK.....

```{r uganda fitted plot}

# make base plot 
plot(dNNdt~population, data=ugandadf, main="Per Capita Growth Rate of Uganda", xlab="Nt (population in millions)", ylab=" Per Capita Growth Rate (dN/Ndt)", xlim=c(0, 50), ylim=c(0,0.05))

# add lines of best fit for both linear models 
#abline(ugandalm_1, col="darkgrey", lwd=2)
#abline(ugandalm_2, col="darkgrey", lwd=2)
abline(ugandalm_3, col="darkgrey", lwd=2)

# add within-sample predictions from both linear models 
dNNdt_pred1<-predict(ugandalm_1)
dNNdt_pred2<-predict(ugandalm_2) 
dNNdt_pred3<-predict(ugandalm_3)

#lines(x=ugandadf$population[ugandadf$year<=1980 & ugandadf$year>1961], y=dNNdt_pred1, col="red", lwd=2) # remove first year, for which there is no prediction (since there was no N-1) 
#lines(x=ugandadf$population[ugandadf$year>1980], y=dNNdt_pred2, col="blue", lwd=2)
lines(x=ugandadf$population[ugandadf$year>1961], y=dNNdt_pred3, col="blue", lwd=2)
```
According to current trends, Uganda will not reach K.
Blue: y=5.43e-05x + 3.14e-02 

```{r mlr}

uganda_mlr <- lm(dNNdt ~ food_pc + education + population, data = ugandadf)

summary(uganda_mlr)

AIC(uganda_mlr)
```

```{r mlr diagnostics}

par(mfrow=c(2,2))
plot(uganda_mlr)

```

```{r collinearity}

pairs(ugandadf[4:6])

```

```{r stargazer, results = 'asis'}

stargazer(uganda_mlr, type = "html")

```

