---
title: "201 Assignment 1 France"
author: "Brad Anderson"
date: "February 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "ESM 201 Assignment 1"
author: "Brad Anderson"
date: "February 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

library(tidyverse)
library(stargazer)
```

```{r data}

countries <- read_csv("~/github/eco1/data/countries.csv")

countries$population <- countries$population/1000

```

```{r create two dataframes}

francedf <- countries %>% 
  filter( country == "France")
  


```

```{r france growth rate}

plot(francedf$year, francedf$population, main = "Total Population of France", xlab="Year", ylab="Population (millions)")

```

```{r Nt-1}

francedf$yearminus1<-(francedf$year-1) # add a column for the previous year 

# Create N_(t-1) column 
francedf$popminus1<-francedf$population[match(francedf$yearminus1, francedf$year)]

```

```{r dn/ndt}

francedf$dNNdt<-log(francedf$population/francedf$popminus1)*1/(francedf$year-francedf$yearminus1)

#Plot results
plot(francedf$population, francedf$dNNdt, xlab="Nt", ylab="dN/Ndt")  # N OR N-1 HERE?

plot(francedf$year, francedf$dNNdt, xlab="year", ylab="dN/Ndt")
```

```{r france models}

francelm_1<-lm(dNNdt~population, data=francedf[francedf$year<=1975,])
francelm_2<-lm(dNNdt~population, data=francedf[francedf$year>1975,])

par(mfrow=c(2,2))
plot(francelm_1) 

par(mfrow=c(2,2)) #Set parameters for plotting a 2x2 window
plot(francelm_2) # need to run this line at the same time as the one above to get 4-panel plot

summary(francelm_2)



```

Diagnostic plots seem OK.....

```{r france fitted plot}

# make base plot 
plot(dNNdt~population, data=francedf, main = "Per Capita Growth Rate of France", xlab="Nt (Population in Millions)", ylab="dN/Ndt (Per Capita Growth Rate)", xlim=c(40, 80), ylim=c(0,0.02))

# add lines of best fit for both linear models 
abline(francelm_1, col="darkgrey", lwd = 2)
abline(francelm_2, col="darkgrey", lwd = 2)

# add within-sample predictions from both linear models 
dNNdt_pred1<-predict(francelm_1)
dNNdt_pred2<-predict(francelm_2) 

lines(x=francedf$population[francedf$year<=1975 & francedf$year>1961], y=dNNdt_pred1, col="red", lwd = 2) # remove first year, for which there is no prediction (since there was no N-1) 
lines(x=francedf$population[francedf$year>1975], y=dNNdt_pred2, col="blue", lwd = 2)

```

France will reach K at a population of about 70 million people.

```{r mlr}

france_mlr <- lm(dNNdt ~ food_pc + education + hiv, data = francedf)

summary(france_mlr)

```

```{r mlr diagnostics}

par(mfrow=c(2,2))
plot(france_mlr)

```

```{r stargazer, results = 'asis'}

stargazer(france_mlr, type = "html")

```